services:
  auth:
    container_name: auth
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - zen-net
    volumes:
      - ./apps/auth:/app
  cv:
    container_name: cv
    build:
      context: .
      dockerfile: ./apps/cv/Dockerfile
    restart: always
    ports:
      - 3002:3002
    networks:
      - zen-net
    volumes:
      - ./apps/cv:/app

  db:
    container_name: db
    image: postgres:latest
    restart: always
    env_file:
      - .env.dev
    ports:
      - 5432:5432
    networks:
      - zen-net
    volumes:
      - pgdata:/var/lib/postgresql/data

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  zen-net:
    external: true

# Define named volumes
volumes:
  pgdata:
